-- Scenario 1:- 
-- Which are the Top 5 customers based on Total order value?

WITH Ordervalue as
(
		SELECT
			CS.CUSTOMER_ID,
			CS.CUSTOMER_NAME,
			SUM(OI.QUANTITY * PS.PRICE - OI.DISCOUNT) AS TOTAL_ORDER_VALUE,
			DENSE_RANK() OVER (
				ORDER BY
					SUM(OI.QUANTITY * PS.PRICE - OI.DISCOUNT) DESC
			) AS RANK_CUSTOMERS
		FROM
			ORDERS OS
			JOIN CUSTOMERS CS ON OS.CUSTOMER_ID = CS.CUSTOMER_ID
			JOIN ORDER_ITEMS OI ON OS.ORDER_ID = OI.ORDER_ID
			JOIN PRODUCTS PS ON OI.PRODUCT_ID = PS.PRODUCT_ID
		WHERE
			OS.ORDER_STATUS = 'Completed'
		GROUP BY
			1,
			2
)

select *
from ordervalue
where Rank_customers<= 5
ORDER BY rank_Customers ASC
